version: "3.2"

services:
  ahpuoj:
    # image: ahpuoj
    build: ./ahpuoj
    tty: true
    depends_on:
      - db
    ports:
      - "8080:80"
    expose:
      - "80"
    volumes: 
      - ${OJ_CODE_PATH_HOST}:${OJ_CODE_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
      - /home/judge/data
    links:
      - db
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    privileged: true
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Shanghai